# Generated by Django 4.2.7 on 2023-12-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignupplatform',
            name='GoogleUserID',
            field=models.PositiveBigIntegerField(default=0, verbose_name='GoogleUserID'),
            preserve_default=False,
        ),
    ]
