# Generated by Django 4.2.7 on 2023-12-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_usersignupplatform_googleuserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignupplatform',
            name='GoogleUserID',
            field=models.CharField(max_length=50, verbose_name='GoogleUserID'),
        ),
    ]
