# Generated by Django 4.2.7 on 2023-12-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_alter_usersignupplatform_googleuserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignupplatform',
            name='GoogleUserID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GoogleUserID'),
        ),
    ]
